/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as DenegadoRouteImport } from './routes/denegado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as CarrerasIndexRouteImport } from './routes/carreras/index'
import { Route as CarrerasNuevaRouteImport } from './routes/carreras/nueva'
import { Route as CompetidoresIndexRouteImport } from './routes/competidores/index'
import { Route as CompetidoresNuevoRouteImport } from './routes/competidores/nuevo'
import { Route as EquiposIndexRouteImport } from './routes/equipos/index'
import { Route as EquiposNuevoRouteImport } from './routes/equipos/nuevo'
import { Route as CarrerasRaceIdIndexRouteImport } from './routes/carreras/$raceId/index'
import { Route as CarrerasRaceIdEditarRouteImport } from './routes/carreras/$raceId/editar'
import { Route as CompetidoresCompetitorIdIndexRouteImport } from './routes/competidores/$competitorId/index'
import { Route as CompetidoresCompetitorIdEditarRouteImport } from './routes/competidores/$competitorId/editar'
import { Route as EquiposTeamIdIndexRouteImport } from './routes/equipos/$teamId/index'
import { Route as EquiposTeamIdEditarRouteImport } from './routes/equipos/$teamId/editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const DenegadoRoute = DenegadoRouteImport.update({
  id: '/denegado',
  path: '/denegado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasIndexRoute = CarrerasIndexRouteImport.update({
  id: '/carreras/',
  path: '/carreras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasNuevaRoute = CarrerasNuevaRouteImport.update({
  id: '/carreras/nueva',
  path: '/carreras/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetidoresIndexRoute = CompetidoresIndexRouteImport.update({
  id: '/competidores/',
  path: '/competidores/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetidoresNuevoRoute = CompetidoresNuevoRouteImport.update({
  id: '/competidores/nuevo',
  path: '/competidores/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposIndexRoute = EquiposIndexRouteImport.update({
  id: '/equipos/',
  path: '/equipos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposNuevoRoute = EquiposNuevoRouteImport.update({
  id: '/equipos/nuevo',
  path: '/equipos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRaceIdIndexRoute = CarrerasRaceIdIndexRouteImport.update({
  id: '/carreras/$raceId/',
  path: '/carreras/$raceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRaceIdEditarRoute = CarrerasRaceIdEditarRouteImport.update({
  id: '/carreras/$raceId/editar',
  path: '/carreras/$raceId/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetidoresCompetitorIdIndexRoute =
  CompetidoresCompetitorIdIndexRouteImport.update({
    id: '/competidores/$competitorId/',
    path: '/competidores/$competitorId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetidoresCompetitorIdEditarRoute =
  CompetidoresCompetitorIdEditarRouteImport.update({
    id: '/competidores/$competitorId/editar',
    path: '/competidores/$competitorId/editar',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquiposTeamIdIndexRoute = EquiposTeamIdIndexRouteImport.update({
  id: '/equipos/$teamId/',
  path: '/equipos/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposTeamIdEditarRoute = EquiposTeamIdEditarRouteImport.update({
  id: '/equipos/$teamId/editar',
  path: '/equipos/$teamId/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/denegado': typeof DenegadoRoute
  '/login': typeof LoginRoute
  '/standings': typeof StandingsRoute
  '/carreras/nueva': typeof CarrerasNuevaRoute
  '/competidores/nuevo': typeof CompetidoresNuevoRoute
  '/equipos/nuevo': typeof EquiposNuevoRoute
  '/carreras/': typeof CarrerasIndexRoute
  '/competidores/': typeof CompetidoresIndexRoute
  '/equipos/': typeof EquiposIndexRoute
  '/carreras/$raceId/editar': typeof CarrerasRaceIdEditarRoute
  '/competidores/$competitorId/editar': typeof CompetidoresCompetitorIdEditarRoute
  '/equipos/$teamId/editar': typeof EquiposTeamIdEditarRoute
  '/carreras/$raceId/': typeof CarrerasRaceIdIndexRoute
  '/competidores/$competitorId/': typeof CompetidoresCompetitorIdIndexRoute
  '/equipos/$teamId/': typeof EquiposTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/denegado': typeof DenegadoRoute
  '/login': typeof LoginRoute
  '/standings': typeof StandingsRoute
  '/carreras/nueva': typeof CarrerasNuevaRoute
  '/competidores/nuevo': typeof CompetidoresNuevoRoute
  '/equipos/nuevo': typeof EquiposNuevoRoute
  '/carreras': typeof CarrerasIndexRoute
  '/competidores': typeof CompetidoresIndexRoute
  '/equipos': typeof EquiposIndexRoute
  '/carreras/$raceId/editar': typeof CarrerasRaceIdEditarRoute
  '/competidores/$competitorId/editar': typeof CompetidoresCompetitorIdEditarRoute
  '/equipos/$teamId/editar': typeof EquiposTeamIdEditarRoute
  '/carreras/$raceId': typeof CarrerasRaceIdIndexRoute
  '/competidores/$competitorId': typeof CompetidoresCompetitorIdIndexRoute
  '/equipos/$teamId': typeof EquiposTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/denegado': typeof DenegadoRoute
  '/login': typeof LoginRoute
  '/standings': typeof StandingsRoute
  '/carreras/nueva': typeof CarrerasNuevaRoute
  '/competidores/nuevo': typeof CompetidoresNuevoRoute
  '/equipos/nuevo': typeof EquiposNuevoRoute
  '/carreras/': typeof CarrerasIndexRoute
  '/competidores/': typeof CompetidoresIndexRoute
  '/equipos/': typeof EquiposIndexRoute
  '/carreras/$raceId/editar': typeof CarrerasRaceIdEditarRoute
  '/competidores/$competitorId/editar': typeof CompetidoresCompetitorIdEditarRoute
  '/equipos/$teamId/editar': typeof EquiposTeamIdEditarRoute
  '/carreras/$raceId/': typeof CarrerasRaceIdIndexRoute
  '/competidores/$competitorId/': typeof CompetidoresCompetitorIdIndexRoute
  '/equipos/$teamId/': typeof EquiposTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/denegado'
    | '/login'
    | '/standings'
    | '/carreras/nueva'
    | '/competidores/nuevo'
    | '/equipos/nuevo'
    | '/carreras/'
    | '/competidores/'
    | '/equipos/'
    | '/carreras/$raceId/editar'
    | '/competidores/$competitorId/editar'
    | '/equipos/$teamId/editar'
    | '/carreras/$raceId/'
    | '/competidores/$competitorId/'
    | '/equipos/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/denegado'
    | '/login'
    | '/standings'
    | '/carreras/nueva'
    | '/competidores/nuevo'
    | '/equipos/nuevo'
    | '/carreras'
    | '/competidores'
    | '/equipos'
    | '/carreras/$raceId/editar'
    | '/competidores/$competitorId/editar'
    | '/equipos/$teamId/editar'
    | '/carreras/$raceId'
    | '/competidores/$competitorId'
    | '/equipos/$teamId'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/denegado'
    | '/login'
    | '/standings'
    | '/carreras/nueva'
    | '/competidores/nuevo'
    | '/equipos/nuevo'
    | '/carreras/'
    | '/competidores/'
    | '/equipos/'
    | '/carreras/$raceId/editar'
    | '/competidores/$competitorId/editar'
    | '/equipos/$teamId/editar'
    | '/carreras/$raceId/'
    | '/competidores/$competitorId/'
    | '/equipos/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  DenegadoRoute: typeof DenegadoRoute
  LoginRoute: typeof LoginRoute
  StandingsRoute: typeof StandingsRoute
  CarrerasNuevaRoute: typeof CarrerasNuevaRoute
  CompetidoresNuevoRoute: typeof CompetidoresNuevoRoute
  EquiposNuevoRoute: typeof EquiposNuevoRoute
  CarrerasIndexRoute: typeof CarrerasIndexRoute
  CompetidoresIndexRoute: typeof CompetidoresIndexRoute
  EquiposIndexRoute: typeof EquiposIndexRoute
  CarrerasRaceIdEditarRoute: typeof CarrerasRaceIdEditarRoute
  CompetidoresCompetitorIdEditarRoute: typeof CompetidoresCompetitorIdEditarRoute
  EquiposTeamIdEditarRoute: typeof EquiposTeamIdEditarRoute
  CarrerasRaceIdIndexRoute: typeof CarrerasRaceIdIndexRoute
  CompetidoresCompetitorIdIndexRoute: typeof CompetidoresCompetitorIdIndexRoute
  EquiposTeamIdIndexRoute: typeof EquiposTeamIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denegado': {
      id: '/denegado'
      path: '/denegado'
      fullPath: '/denegado'
      preLoaderRoute: typeof DenegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras/': {
      id: '/carreras/'
      path: '/carreras'
      fullPath: '/carreras/'
      preLoaderRoute: typeof CarrerasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras/nueva': {
      id: '/carreras/nueva'
      path: '/carreras/nueva'
      fullPath: '/carreras/nueva'
      preLoaderRoute: typeof CarrerasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competidores/': {
      id: '/competidores/'
      path: '/competidores'
      fullPath: '/competidores/'
      preLoaderRoute: typeof CompetidoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competidores/nuevo': {
      id: '/competidores/nuevo'
      path: '/competidores/nuevo'
      fullPath: '/competidores/nuevo'
      preLoaderRoute: typeof CompetidoresNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/': {
      id: '/equipos/'
      path: '/equipos'
      fullPath: '/equipos/'
      preLoaderRoute: typeof EquiposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/nuevo': {
      id: '/equipos/nuevo'
      path: '/equipos/nuevo'
      fullPath: '/equipos/nuevo'
      preLoaderRoute: typeof EquiposNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras/$raceId/': {
      id: '/carreras/$raceId/'
      path: '/carreras/$raceId'
      fullPath: '/carreras/$raceId/'
      preLoaderRoute: typeof CarrerasRaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras/$raceId/editar': {
      id: '/carreras/$raceId/editar'
      path: '/carreras/$raceId/editar'
      fullPath: '/carreras/$raceId/editar'
      preLoaderRoute: typeof CarrerasRaceIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competidores/$competitorId/': {
      id: '/competidores/$competitorId/'
      path: '/competidores/$competitorId'
      fullPath: '/competidores/$competitorId/'
      preLoaderRoute: typeof CompetidoresCompetitorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competidores/$competitorId/editar': {
      id: '/competidores/$competitorId/editar'
      path: '/competidores/$competitorId/editar'
      fullPath: '/competidores/$competitorId/editar'
      preLoaderRoute: typeof CompetidoresCompetitorIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/$teamId/': {
      id: '/equipos/$teamId/'
      path: '/equipos/$teamId'
      fullPath: '/equipos/$teamId/'
      preLoaderRoute: typeof EquiposTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/$teamId/editar': {
      id: '/equipos/$teamId/editar'
      path: '/equipos/$teamId/editar'
      fullPath: '/equipos/$teamId/editar'
      preLoaderRoute: typeof EquiposTeamIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  DenegadoRoute: DenegadoRoute,
  LoginRoute: LoginRoute,
  StandingsRoute: StandingsRoute,
  CarrerasNuevaRoute: CarrerasNuevaRoute,
  CompetidoresNuevoRoute: CompetidoresNuevoRoute,
  EquiposNuevoRoute: EquiposNuevoRoute,
  CarrerasIndexRoute: CarrerasIndexRoute,
  CompetidoresIndexRoute: CompetidoresIndexRoute,
  EquiposIndexRoute: EquiposIndexRoute,
  CarrerasRaceIdEditarRoute: CarrerasRaceIdEditarRoute,
  CompetidoresCompetitorIdEditarRoute: CompetidoresCompetitorIdEditarRoute,
  EquiposTeamIdEditarRoute: EquiposTeamIdEditarRoute,
  CarrerasRaceIdIndexRoute: CarrerasRaceIdIndexRoute,
  CompetidoresCompetitorIdIndexRoute: CompetidoresCompetitorIdIndexRoute,
  EquiposTeamIdIndexRoute: EquiposTeamIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
